### ISSUE TITLE
Why is React experimental version included?

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [reason-seoul/cra-template-rescript#1]
Hi. Thanks for this. Any reason why the react experimental version used in the template?

**Comment by cometkim** [comment]
Hi @a-c-sreedhar-reddy, well, Reason React started [supporting it first in v0.8.0](https://reasonml.github.io/reason-react/blog/2020/05/05/080-release)

Unfortunately It was broken by the `unstable_` prefix, but I thought it was a good place to include an example of FFI bindings.

**Comment by cometkim** [comment]
closing. feel free to open another/further question :)
